window.portfolioProjects = [
  {
    title: "Rock Paper Scissors",
    category: "JavaScript Game",
    description:
      "An interactive browser game built with JavaScript to practice DOM manipulation, game logic, score handling, and user feedback.",
    image: "port-image2.jpg",
    alt: "Screenshot of rock paper scissors game project",
    tech: ["HTML", "CSS", "JavaScript"],
    liveUrl: "https://sujalshk.github.io/ROCK_PAPER_SCISSOR-/",
    githubUrl: "https://github.com/sujalshk/ROCK_PAPER_SCISSOR-",
    featured: true,
  },
  {
    title: "Amazon Clone",
    category: "Frontend Project",
    description:
      "An e-commerce interface built to practice navigation, product cards, layout structure, and responsive design.",
    image: "port-image1.jpg",
    alt: "Screenshot of Amazon clone project",
    tech: ["HTML", "CSS", "JavaScript"],
    liveUrl: "https://sujalshk.github.io/amazon-clone-sujal/",
    githubUrl: "https://github.com/sujalshk/amazon-clone-sujal",
    featured: true,
  },
  {
    title: "Personal Portfolio",
    category: "Portfolio Website",
    description:
      "A professional portfolio website designed to showcase my skills, projects, resume, and contact information.",
    image: "port-image3.jpg",
    alt: "Screenshot representing Sujal Shakya portfolio website",
    tech: ["HTML", "CSS", "JavaScript"],
    liveUrl: "/#home",
    githubUrl: "https://github.com/sujalshk",
    featured: true,
  },
  {
    title: "Ghost Student Prevention System",
    category: "AI Web App",
    description:
      "An AI-powered dashboard that helps teachers identify students at risk of disengagement and generate supportive outreach suggestions.",
    image: "port-image6.jpg",
    alt: "Preview image for Ghost Student Prevention System",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Gemini API"],
    liveUrl: "#",
    githubUrl: "https://github.com/sujalshk",
    featured: true,
  },
  {
    title: "Weather Dashboard",
    category: "API Project",
    description:
      "A weather application that displays current weather, forecast data, temperature, humidity, and location-based results using a weather API.",
    image: "port-image4.jpg",
    alt: "Preview image for Weather Dashboard project",
    tech: ["React", "API", "Tailwind CSS"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "Task Manager App",
    category: "Productivity App",
    description:
      "A simple task management app where users can add, edit, delete, and mark tasks as completed with a clean user interface.",
    image: "port-image5.jpg",
    alt: "Preview image for Task Manager App project",
    tech: ["React", "JavaScript", "Local Storage"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "Movie Search App",
    category: "API Project",
    description:
      "A movie search web app that allows users to search movies, view ratings, release dates, posters, and short descriptions.",
    image: "port-image1.jpg",
    alt: "Preview image for Movie Search App project",
    tech: ["React", "API", "CSS"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "Expense Tracker",
    category: "Finance App",
    description:
      "A personal finance tracker that helps users record income and expenses, calculate balance, and view spending history.",
    image: "port-image2.jpg",
    alt: "Preview image for Expense Tracker project",
    tech: ["JavaScript", "HTML", "CSS"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "Recipe Finder",
    category: "Food App",
    description:
      "A recipe search app where users can search meals, view ingredients, instructions, and save favorite recipes.",
    image: "port-image3.jpg",
    alt: "Preview image for Recipe Finder project",
    tech: ["React", "API", "Tailwind CSS"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "Student Grade Calculator",
    category: "Education Tool",
    description:
      "A grade calculator that helps students calculate their current grade, final exam requirement, and overall course performance.",
    image: "port-image4.jpg",
    alt: "Preview image for Student Grade Calculator project",
    tech: ["JavaScript", "HTML", "CSS"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "Chat UI Design",
    category: "Frontend UI",
    description:
      "A modern chat interface design with message bubbles, user avatars, timestamps, and responsive layout.",
    image: "port-image5.jpg",
    alt: "Preview image for Chat UI Design project",
    tech: ["React", "Tailwind CSS", "UI Design"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "AI Resume Analyzer",
    category: "AI Tool",
    description:
      "An AI-powered tool concept that reviews resumes, gives improvement suggestions, and highlights missing skills for job applications.",
    image: "port-image6.jpg",
    alt: "Preview image for AI Resume Analyzer project",
    tech: ["Next.js", "AI API", "Tailwind CSS"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "Campus Event Website",
    category: "Event Website",
    description:
      "A landing page for campus events with event details, schedule, location, registration button, and photo highlights.",
    image: "portIMG2.jpg",
    alt: "Preview image for Campus Event Website project",
    tech: ["React", "Tailwind CSS", "Responsive Design"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    title: "Photo Gallery App",
    category: "Gallery Project",
    description:
      "A responsive image gallery where users can view event photos, open images in a modal, and browse photos by category.",
    image: "port-image1.jpg",
    alt: "Preview image for Photo Gallery App project",
    tech: ["React", "JavaScript", "CSS Grid"],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
  },
];
